#ifndef GUI_CONTROLS_H
#define GUI_CONTROLS_H

enum {
    DLG_MAIN_MENU_TS_FILE_OPEN_ID = 4000,
    DLG_MAIN_MENU_TS_FILE_SAVE_ID,
    DLG_MAIN_MENU_SETTINGS_ID,
    DLG_MAIN_MENU_DOCUMENTATION_ID,
    DLG_MAIN_TOOLBAR_CONFIG_MAIN_ID,
    DLG_MAIN_TOOLBAR_TS_OPEN_MAIN_ID,
    DLG_MAIN_TOOLBAR_TS_SAVE_ID,
    DLG_MAIN_TEXTCTRL_PACKET_CURRENT_ID,
    DLG_MAIN_TEXTCTRL_PACKETS_COUNT_ID,
    DLG_MAIN_TOOLBAR_LIST_ALL_BACKWARD_ID,
    DLG_MAIN_TOOLBAR_LIST_BACKWARD_ID,
    DLG_MAIN_TOOLBAR_LIST_ALL_FORWARD_ID,
    DLG_MAIN_TOOLBAR_LIST_FORWARD_ID,

    DLG_CONFIG_TOOL_SAVE_ID,
    DLG_CONFIG_TOOL_CLOSE_ID
};

#endif